[build]
  publish = "."
  command = "npm run build"
  functions = "netlify/functions"
  ignore = "node netlify/ignore-draft-pr.js"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/cows"
  to = "/.netlify/functions/cows"
  status = 200
  force = true

[[redirects]]
  from = "/api/track"
  to = "/.netlify/functions/track"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/tracks"
  to = "/.netlify/functions/track"
  status = 200
  force = true
